_reference_os: &reference_os
  linux
_reference_arch: &reference_arch
  amd64
_reference_JDK: &reference_JDK
  JDK="adopt@1.11"

language: minimal

git:
  depth: false
  autocrlf: input

os:
  - *reference_os
  - osx
  - windows

dist: focal

arch:
  - *reference_arch
  - arm64

env:
  global:
    - GRAVIS_REPO="https://github.com/DanySK/Gravis-CI.git"
    - GRAVIS="$HOME/gravis"
  matrix:
    - JDK="adopt@1.8"
    - *reference_JDK
    - JDK="adopt@1.14"
    - JDK="adopt-openj9@1.8"
    - JDK="adopt-openj9@1.11"
    - JDK="adopt-openj9@1.14"

_reference_machine: &reference_machine
  arch: *reference_arch
  os: *reference_os
  env: *reference_JDK

jobs:
  exclude:
    - arch: arm64
      env: JDK="adopt-openj9@1.8"
    - arch: arm64
      env: JDK="adopt-openj9@1.14"
    - <<: *reference_machine
      stage: test
  include:
    - <<: *reference_machine
      stage: check
      script:
        - travis_retry ./gradlew check

stages:
  - check
  - test

before_install:
  - travis_retry git clone --depth 1 $GRAVIS_REPO $GRAVIS
  - source $GRAVIS/install-jdk

install:
  true

script:
  - travis_retry ./gradlew check